### ISSUE TITLE
Feedback Validation

### ISSUE THREAD

**Issue by NavneethJayendran** [Togira/CS125-Research#12]
I posted this somewhere else but can't seem to find it anymore. But anyway, I have a couple low level issues to address:

1: (How) do we handle duplicate entries from the same student for the same lecture? I would recommend something like concatenating feedback from those entries and taking the last entry for the purposes of rating and partner selection. Or does the feedback app itself handle this?

2: (How) do we handle partner mismatches? For example, what if a Student writes down the netID of a person who hasn't attended Lecture or who doesn't reciprocate in his entry? I doubt the Feedback app handles this. An easy way (conceptually) to handle this would be simply delete unpaired entries from Lectures. Implementing this would be somewhat easy if we had a way to map (Student, Lecture)->FeedbackEntry. I will propose such a map shortly.

3: We should consider ignoring/marking lecture feedback given in the first ~15 minutes of class for obvious reasons.

**Comment by pranaygp** [comment]
3.1: We would need to be able to map out a FeedbackEntry toa particular lecture to accomplish 3. As of now, we're treating every lecture after 9AM on a certain day, as the same lecture. Implementing point 3 would require us to be able to map out a feedback entry to say, for instance, the 9AM - 10AM lecture or the 10AM - 11AM lecture. **Not sure if this is necessary yet or if point 3 is important enough that it requires us to do so.**

**Comment by pranaygp** [comment]
Also, for point 2. Do we need to do this? The feedback, even if the partner didn't fill in their part, might still be important data/feedback as far as research is concerned. I think it's only important to disregard such instances when it comes to attendance/course grades.

**Comment by NavneethJayendran** [comment]
I just realized the third one isn't feasible because there are two lectures. So disregard it.

I don't know how we approach the second one, but I assumed that if the partner's netID must exist, the partner must also be a valid partner (otherwise we might as well accept all entries with valid primary IDs). Aside from that asymmetry, I agree it's not a priority.

For the first, I imagine all we need to do is map each packet of entries to Students, check each Student's entries before we insert them into a Lecture,

**Comment by NavneethJayendran** [comment]
merge entries from the same Lecture into one "effective" entry for each Student, and then insert all the effective entries into the latest Lecture. This suggests that we might want a FeedbackEntry(FeedbackEntry[]) constructor and some scan method for Student.

**Comment by pranaygp** [comment]
I'm not sure how a FeedbackEntry(FeedbackEntry[]) constructor would help. I was thinking of a method that would reside in the `Student` class which takes `FeedbackEntry[]` as a parameter.

I'm probably just thinking of a slightly (but trivially) different implementation.

I'll let you have the option to work on this if you want to since you came up with this issue. If you're busy or if you're okay with me trying my hand at this, go ahead assign me to this issue and lemme know :smiley:
