### ISSUE TITLE
Ignore generated files

### ISSUE THREAD

**Issue by pranaygp** [Togira/CS125-Research#5]
> .metadata files, .class files and other generated files should probably be ignored

I noticed that when I checked out @NavneethJayendran 's branch, worked on it and made a commit, it modified a whole bunch of files.

**We should add a .gitignore for generated files**

Here's a link that might come in handy for anyone that wants to do this

http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by Togira** [comment]
A pull request was submitted.

**Comment by pranaygp** [comment]
#7 implements this.
